blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/your-org/next-dev/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/your-org/next-dev/wiki
    about: Check our documentation for answers to common questions.
