name: Next.js CI/CD Pipeline

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:
    inputs:
      deploy_to_production:
        description: 'Deploy to production'
        type: boolean
        default: false
        required: true

# Add global permissions for GitHub token
permissions:
  contents: write
  pull-requests: write
  deployments: write
  issues: write
  statuses: write

jobs:
  # Lint and Test job - runs for all events
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: false

      - name: Run Jest tests
        id: jest
        run: npm test -- --testPathIgnorePatterns="/pages/"

      - name: Generate test coverage
        run: npm run test:coverage

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  # Security scanning job
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --production
        continue-on-error: true

      - name: Run Snyk scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  # Build job
  build:
    name: Build Application
    needs: [lint-and-test, security-scan]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    outputs:
      build-success: ${{ steps.build-status.outputs.success }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        id: build-app
        env:
          NEXT_PUBLIC_CONVEX_URL: ${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
          NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }}
          NEXT_PUBLIC_GOOGLE_AUTH_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_AUTH_KEY }}
        run: |
          set +e
          npm run build
          build_exit_code=$?
          set -e
          echo "Build exit code: $build_exit_code"
          if [ $build_exit_code -eq 0 ]; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
            exit $build_exit_code
          fi

      - name: Create build artifact
        if: steps.build-app.outputs.success == 'true'
        run: |
          tar -czf build-output.tar.gz .next
          echo "Build artifact created successfully"

      - name: Upload build artifact
        if: steps.build-app.outputs.success == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build-output.tar.gz
          retention-days: 7

      - name: Set build status
        id: build-status
        run: |
          if [ "${{ steps.build-app.outputs.success }}" == "true" ]; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

  # Performance testing job
  performance-test:
    name: Performance Testing
    needs: [build]
    if: needs.build.outputs.build-success == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Extract build artifact
        run: tar -xzf build-output.tar.gz

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.13.x

      - name: Create Lighthouse config
        run: |
          cat > lighthouserc.json << 'EOL'
          {
            "ci": {
              "collect": {
                "url": ["http://localhost:3000"],
                "numberOfRuns": 1
              },
              "assert": {
                "preset": "lighthouse:no-pwa",
                "assertions": {
                  "csp-xss": "off",
                  "document-title": "off",
                  "errors-in-console": "off",
                  "font-size": "off",
                  "html-has-lang": "off",
                  "meta-description": "off",
                  "tap-targets": "off",
                  "viewport": "off",
                  "unused-javascript": "off",
                  "total-byte-weight": "off",
                  "bootup-time": "off",
                  "dom-size": "off",
                  "mainthread-work-breakdown": "off",
                  "max-potential-fid": "off",
                  "modern-image-formats": "off",
                  "render-blocking-resources": "off",
                  "server-response-time": "off",
                  "largest-contentful-paint": "off"
                }
              },
              "upload": {
                "target": "temporary-public-storage"
              }
            }
          }
          EOL

      - name: Start Next.js server
        run: |
          npm ci
          npm run start &
          sleep 10

      - name: Run Lighthouse CI
        run: |
          lhci autorun
        continue-on-error: true

      - name: Save Lighthouse report
        run: |
          mkdir -p lighthouse-reports
          cp -r .lighthouseci/reports/* lighthouse-reports/ || true

      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: lighthouse-reports/
          retention-days: 7

  # Deploy preview for development branch
  deploy-preview:
    name: Deploy Preview
    needs: [build, performance-test]
    if: |
      needs.build.outputs.build-success == 'true' &&
      github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      deployments: write
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Extract build artifact
        run: tar -xzf build-output.tar.gz

      - name: Deploy to Vercel (Preview)
        id: preview-deployment
        uses: amondnet/vercel-action@v25
        env:
          NEXT_PUBLIC_CONVEX_URL: ${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
          NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }}
          NEXT_PUBLIC_GOOGLE_AUTH_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_AUTH_KEY }}
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GH_PAT }}
          github-comment: true
          working-directory: ./
          vercel-args: '--env NEXT_PUBLIC_GOOGLE_AUTH_KEY="${{ secrets.NEXT_PUBLIC_GOOGLE_AUTH_KEY }}" --env NEXT_PUBLIC_CONVEX_URL="${{ secrets.NEXT_PUBLIC_CONVEX_URL }}" --env NEXT_PUBLIC_GEMINI_API_KEY="${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }}"'

      - name: Wait for deployment to be ready
        run: |
          echo "Waiting for deployment to be ready..."
          sleep 30

      - name: Health check
        id: health-check
        run: |
          DEPLOY_URL="${{ steps.preview-deployment.outputs.preview-url }}"
          echo "Checking health of $DEPLOY_URL"

          MAX_RETRIES=5
          RETRY_DELAY=10

          for ((i=1; i<=MAX_RETRIES; i++)); do
            echo "Health check attempt $i of $MAX_RETRIES"
            if curl -s -f -o /dev/null "$DEPLOY_URL"; then
              echo "status=success" >> $GITHUB_OUTPUT
              break
            else
              if [ $i -lt $MAX_RETRIES ]; then
                echo "Health check failed. Waiting for $RETRY_DELAY seconds before retry..."
                sleep $RETRY_DELAY
              else
                echo "Health check failed after $MAX_RETRIES attempts."
                echo "status=failure" >> $GITHUB_OUTPUT
              fi
            fi
          done

      - name: Create GitHub Deployment Status
        if: steps.health-check.outputs.status == 'success'
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GH_PAT }}
          state: "success"
          deployment-id: ${{ github.run_id }}
          environment-url: ${{ steps.preview-deployment.outputs.preview-url }}
          description: "Preview deployment successful"

      - name: Store deployment URL for rollback
        if: steps.health-check.outputs.status == 'success'
        run: |
          DEPLOY_URL="${{ steps.preview-deployment.outputs.preview-url }}"
          echo "$DEPLOY_URL" > .vercel-latest-deployment
          echo "Latest deployment URL: $DEPLOY_URL"

      - name: Upload deployment URL artifact
        if: steps.health-check.outputs.status == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: deployment-url
          path: .vercel-latest-deployment
          retention-days: 30

  # Deploy to production environment
  deploy-production:
    name: Deploy to Production
    needs: [build, performance-test]
    if: |
      needs.build.outputs.build-success == 'true' &&
      ((github.event_name == 'pull_request' && (github.base_ref == 'main' || github.base_ref == 'master')) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_to_production == 'true'))
    runs-on: ubuntu-latest

    permissions:
      contents: write
      deployments: write
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Extract build artifact
        run: tar -xzf build-output.tar.gz

      - name: Deploy to Vercel (Production)
        id: prod-deployment
        uses: amondnet/vercel-action@v25
        env:
          NEXT_PUBLIC_CONVEX_URL: ${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
          NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }}
          NEXT_PUBLIC_GOOGLE_AUTH_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_AUTH_KEY }}
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GH_PAT }}
          github-comment: true
          working-directory: ./
          vercel-args: '--prod --env NEXT_PUBLIC_GOOGLE_AUTH_KEY="${{ secrets.NEXT_PUBLIC_GOOGLE_AUTH_KEY }}" --env NEXT_PUBLIC_CONVEX_URL="${{ secrets.NEXT_PUBLIC_CONVEX_URL }}" --env NEXT_PUBLIC_GEMINI_API_KEY="${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }}"'

      - name: Wait for deployment to be ready
        run: |
          echo "Waiting for deployment to be ready..."
          sleep 30

      - name: Health check
        id: health-check
        run: |
          DEPLOY_URL="${{ steps.prod-deployment.outputs.preview-url }}"
          echo "Checking health of $DEPLOY_URL"

          MAX_RETRIES=5
          RETRY_DELAY=10

          for ((i=1; i<=MAX_RETRIES; i++)); do
            echo "Health check attempt $i of $MAX_RETRIES"
            if curl -s -f -o /dev/null "$DEPLOY_URL"; then
              echo "status=success" >> $GITHUB_OUTPUT
              break
            else
              if [ $i -lt $MAX_RETRIES ]; then
                echo "Health check failed. Waiting for $RETRY_DELAY seconds before retry..."
                sleep $RETRY_DELAY
              else
                echo "Health check failed after $MAX_RETRIES attempts."
                echo "status=failure" >> $GITHUB_OUTPUT
              fi
            fi
          done

      - name: Create GitHub Deployment Status
        if: steps.health-check.outputs.status == 'success'
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GH_PAT }}
          state: "success"
          deployment-id: ${{ github.run_id }}
          environment-url: ${{ steps.prod-deployment.outputs.preview-url }}
          description: "Production deployment successful"

      - name: Store deployment URL for rollback
        if: steps.health-check.outputs.status == 'success'
        run: |
          DEPLOY_URL="${{ steps.prod-deployment.outputs.preview-url }}"
          echo "$DEPLOY_URL" > .vercel-latest-production-deployment
          echo "Latest production deployment URL: $DEPLOY_URL"

      - name: Upload deployment URL artifact
        if: steps.health-check.outputs.status == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: production-deployment-url
          path: .vercel-latest-production-deployment
          retention-days: 30
